### ISSUE TITLE
Cannot read property 'tapAsync' of undefined when using with HTML Webpack Plugin 4.0.0-alpha.2

### ISSUE THREAD

**Issue by ajaybc** [slackhq/csp-html-webpack-plugin#20]
### Description

I used the latest create-react-app CLI to bootstrap my project and then I ejected it. The latest create-react-app uses "html-webpack-plugin" version 4.0.0-alpha.2. When I use "csp-html-webpack-plugin" with it I am getting the following error

> Cannot read property 'tapAsync' of undefined

I have already tried placing "csp-html-webpack-plugin" at the end of the plugins list after "html-webpack-plugin" and still I am getting the same issue.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/csp-html-webpack-plugin/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

slackhq/csp-html-webpack-plugin version: 2.3.0

node version: 8.12.0

OS version(s): OSX Mojave

#### Steps to reproduce:

1. Bootstrap an app with the latest create-react-app CLI
2. Eject the application
3. Then try using "csp-html-webpack-plugin"

#### Expected result:

Expected the build to complete

#### Actual result:

Got the error "Cannot read property 'tapAsync' of undefined"

**Comment by AnujRNair** [comment]
Thanks for reporting! 

We have PR https://github.com/slackhq/csp-html-webpack-plugin/pull/16 in flight which will include webpack 4 support and fix this error :)

**Comment by ajaybc** [comment]
@AnujRNair Thanks for the reply. Can we have a beta version of the "csp-html-webpack-plugin" with the support. Pretty please :)

**Comment by sibiraj-s** [comment]
@ajaybc `html-webpack-plugin` final version will be available by the end of this month. also @AnujRNair 
clearly stated here https://github.com/slackhq/csp-html-webpack-plugin/pull/16#issuecomment-423284374

> but won't actually merge until HTMLWebpackPlugin comes out of alpha and beta, just incase there are unforseen API updates

he is waiting for the final release. So you may have to wait 10 more days. 

Also @AnujRNair. I am pretty sure, that there will be no api changes to the plugin. based on https://github.com/jantimon/html-webpack-plugin/pull/953#issuecomment-429716203

**Comment by AnujRNair** [comment]
HtmlWebpackPlugin 4 functionality has been merged!
