### ISSUE TITLE
package.json metadata missing?

### ISSUE THREAD

**Issue by hugopeixoto** [slackhq/csp-html-webpack-plugin#42]
### Description

Hi :) I got notified of 3.0.0 by dependabot in one of my repositories.

Dependabot was unable to show me the changelog and commits. I noticed that the link to the repository was https://github.com/anuj/csp-html-webpack-plugin, but that repository seems to no longer exist. I think it was migrated to `slackhq`.

I don't know what caused dependabot to show the old URL, but maybe adding some URLs to package.json helps? I noticed in https://www.npmjs.com/package/csp-html-webpack-plugin that there are no links in the sidebar.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/csp-html-webpack-plugin/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by AnujRNair** [comment]
Thanks! Fixed with https://github.com/slackhq/csp-html-webpack-plugin/pull/43
