### ISSUE TITLE
Enable Report-Only

### ISSUE THREAD

**Issue by RenoMeyer** [slackhq/csp-html-webpack-plugin#52]
### Description

In order to properly test the introduction of new CSPs, it would be amazing if the plugin was able to also output a meta tag with `http-equiv="Content-Security-Policy-Report-Only"`. Ideally, these tags could co-exist, so you can leave the already active CSPs in place, while testing new policies at the same time, i.e. it would allow two separate configurations.

I'm happy to contribute if the feature fits the scope of this plugin and nothing is in the pipeline yet...

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/csp-html-webpack-plugin/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by AnujRNair** [comment]
Hi @RenoMeyer!

We would gladly accept a PR for this feature.

Thoughts on the following?
- Enable this meta tag if a new option `enabledReportOnly` is set to `true` (default `false`)
- Ensure that if this flag is enabled, the developer has also set a `report-uri` AND `report-to` policy
  - We could have an extra option to disable checking for `report-uri` or `report-to` since the former is being depreciated and replaced by the latter.
- Run through the same logic which currently handles finding an existing / adding a new CSP metatag to add this report only meta tag

Looking forward to what you think!

**Comment by andrebazoli** [comment]
Hi @AnujRNair,

I tried to be a good citizen and add this feature but I got the following error:
![image](https://user-images.githubusercontent.com/50202384/74936942-62e7cd80-53eb-11ea-9695-c17b116eb168.png)

As you can see on [policy_applies_to_a_wide_variety_of_resources](https://developers.google.com/web/fundamentals/security/csp#policy_applies_to_a_wide_variety_of_resources) the `report-uri` cannot be used inside meta tags.

**Comment by AnujRNair** [comment]
Thanks for investigating! I will close this PR for now, given it looks like we cannot implement this. We can revisit if that ever changes.

**Comment by RenoMeyer** [comment]
Sorry for my long absence and also thank you @andrebazoli for your attempt...

**Comment by AnujRNair** [comment]
https://github.com/slackhq/csp-html-webpack-plugin/releases/tag/v4.0.0 was just released a short while ago which allows you to add your own `processFn` - this allows you to control how the CSP is added to your app.

Devs have been extracting this into a separate file and inputting into headers - you should be able to add report only mode through this

**Comment by samsaggace** [comment]
Hi @AnujRNair, 
I'm trying to implement your proposition to use the processFn to extract the CSP into a file (that I will include in nginx) but I have some issue telling webpack I generated a new file...
From what I understand from webpack, when a new file is added, it needs to be added to the `assets` using : 
`compilation.emitAsset(file, content);`
But in the processFn, this compilation object is not binded so I can't do it...
Is there another way to do so ? 
Is it possible may be to add this compilation object to the parameters of the processFn callback ?

Thanks for your help !

**Comment by samsaggace** [comment]
I've tried a little something that works fine for my use-case : 
https://github.com/samsaggace/csp-html-webpack-plugin/commit/4f653f7f0f4ef4fad3cfca88d2b30c9b055dacf3

And then I just need to do this in my webpack conf : 
```
const RawSource = require("webpack-sources").RawSource;

function dumpCSP(builtPolicy, htmlPluginData, obj, compilation) {
  header = "add_header Content-Security-Policy-Report-Only \"" + builtPolicy + "\";"
  compilation.emitAsset("nginx-csp-header.conf", new RawSource(header))
}
```

If it's something that could be interesting for the community please tell me and I can prepare it for a clean PR.

Thanks

**Comment by AnujRNair** [comment]
Hi @samsaggace - that sounds like a great addition to me - please open a PR with matching tests and I will review!

**Comment by samsaggace** [comment]
Hi @AnujRNair, I'm back from holidays and submitted the PR, hope it will be fine
