### ISSUE TITLE
XHTML mode is not honored

### ISSUE THREAD

**Issue by sjinks** [slackhq/csp-html-webpack-plugin#61]
### Description

Currently the plugin does not honor "XHTML mode": for example, if we have a configuration like this:

```javascript
            new HtmlWebpackPlugin({
                filename: 'index.html',
                template: './src/index.html',
                xhtml: true,
            })
```

the plugin will still output html-style tags (e.g., `<meta charset="utf-8">` instead of `<meta charset="utf-8"/>`).

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [x] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/csp-html-webpack-plugin/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

slackhq/csp-html-webpack-plugin version: 4.0.0

node version: 12.17.0

OS version(s): any

#### Steps to reproduce:

See above - create a Webpack config with `xhtml: true` set for `html-webpack-plugin`

#### Expected result:

The generated HTML should have self-closing tags where appropriate, like

```html
<meta charset="utf-8"/>
```

#### Actual result:

The generated markup does not honor `xhtml: true`:

```html
<meta charset="utf-8">
```

**Comment by AnujRNair** [comment]
Fixed in https://github.com/slackhq/csp-html-webpack-plugin/pull/75
