### ISSUE TITLE
Peer Dependency for WebPack v5

### ISSUE THREAD

**Issue by david-fong** [slackhq/csp-html-webpack-plugin#68]
### Description

The current package.json doesn't specify webpack 5 as a peer dependency. Is this intentional?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/csp-html-webpack-plugin/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by AnujRNair** [comment]
This was not intentional - I haven't gotten around to testing this with webpack 5 yet. I'll accept a pull request to add the peer dependency if you've tested it!

**Comment by david-fong** [comment]
> This was not intentional - I haven't gotten around to testing this with webpack 5 yet. I'll accept a pull request to add the peer dependency if you've tested it!

I've tested it with webpack 5 and it is working for me as expected. Webpack doesn't complain about it either. I'll make a PR!
