### ISSUE TITLE
Cheerio 1.0.0-rc.4

### ISSUE THREAD

**Issue by slandmann** [slackhq/csp-html-webpack-plugin#73]
Hi,

Can you please upgrade to Cheerio 1.0.0-rc.4?

Cheerio 1.0.0-rc.4 uses Lodash 4.17.20 which fixes vulnerabilities.

**Comment by AnujRNair** [comment]
It doesn't look like `cheerio 1.0.0-rc.4` has been published to npm yet - are you seeing otherwise?
