### ISSUE TITLE
Consider adding documentation for automatic webpack server restart

### ISSUE THREAD

**Issue by maudnals** [slackhq/csp-html-webpack-plugin#76]
### Description

Hi, thank you for this great plugin!!
When tweaking my CSP in `webpack.config.js`, I found myself stopping and restarting my webpack server for my CSP changes to be taken into account. I ended up using nodemon to do this automatically and save time. I think this may be a common workflow, since setting up CSP involves tweaking and back-and-forth.
**Do you think it would make sense for the README to include a note on how to set this up?**

This is what I did:
* Created `nodemon.json` in my project root:
```json
{
  "watch": ["webpack.config.js"],
  "exec": "node scripts/start.js" // = what was in my package.json's start script
}
```
* In package.json, added a new script:
```json
 "start:watch:webpack": "nodemon",
```
* Used `npm run start:watch:webpack` when setting up my CSP.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackhq/csp-html-webpack-plugin/blob/master/.github/CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by AnujRNair** [comment]
Thanks for the feedback!

I think it's common to expect to have to restart `webpack-dev-server` each time you change a configuration option, or recompile assets if you're writing to disk.

Although this would make the dev flow easier, it's not something which is specific to this plugin alone - all changes to webpack usually require a restart!

For this reason, I don't think we should add this to the readme, although we do have a paper trail here in this issue for anyone who is interested in hot reloading their csp changes :)
