### ISSUE TITLE
Regression in 5.0.1

### ISSUE THREAD

**Issue by david-fong** [slackhq/csp-html-webpack-plugin#80]
### Description

Describe your issue here.

- [x] bug

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

slackhq/csp-html-webpack-plugin version: 5.0.1

node version: 14

OS version(s): windows 10

#### Steps to reproduce:

```
git checkout http://github.com/david-fong/snakey3.git
cd snakey3
git checkout 396fe45
./scripts/pack -t
```

2. open `file:///.../snakey3/dist/client/index.html` and observe error for incorrect script sha in the browser devtools.
3. `git checkout @~ && ./scripts/pack`, then open again and observe that there is no such error.

I'm not sure why this happens. 

#### Expected result:

I expect that bumping from version 5.0.0 to 5.0.1 shouldn't break anything.

#### Actual result:

Something broke.

#### Attachments:

<img src="https://user-images.githubusercontent.com/42986768/103400809-55b36900-4afb-11eb-841d-d4a4e62ee0c5.jpg" height="300">

**Comment by AnujRNair** [comment]
Hi @david-fong - thanks for the report.

I'm having trouble reproducing the error - specifically on step 2, where is `file:///.../snakey3/index.html` located? One of the index.html files in the dist folder?

I ran the build on `396fe45` and the previous commit, opened `dist/client/index.html` and both seemed to work as intended.

Let me know which file you're specifically referencing, and I'll take another look

**Comment by david-fong** [comment]
Hi @AnujRNair, thanks for taking a look at this so quickly!

Yes, the file should be `.../snakey3/dist/client/index.html`- not `.../snakey3/index.html`. Sorry about that! I have fixed the typo in the description.

It's interesting that you don't experience the error. Does that change if you explicitly run `pnpm install --frozen-lockfile` before each test? (I think the git hook I set up to automate that task is broken).

**Comment by samsaggace** [comment]
Hi @AnujRNair and @david-fong,

FYI, I couldn't reproduce the isssue either, i've tried with and without the frozen lockfile, by following the dev-guide (pnpm buil)  and by running the script (pack.sh).

**Comment by david-fong** [comment]
Okay. Thank you both so much for taking the time to try out my repro. This makes me suspect that the issue may not be specifically with csp-html-webpack-plugin. I will investigate this further on my own (which may take some time, since I don't have much time for it this week). If it is okay with you, this issue can be closed, and if I find out what the cause of the issue is, I'll either comment in this thread or open a new issue.

**Comment by AnujRNair** [comment]
Sounds great, thanks! If you confirm it to be csp-html-webpack-plugin, comment here, and I'll reopen this issue :)
